#!/usr/bin/env zsh

print "/* Auto-generated by timegen.sh begin */"
# print "/*"
# Insert the script into a comment, and account for nested comments
# sed -E 's/^/ * /g; s@\*\/@\*\/\/\*@g' $0
# print " */"
for halve in AM PM; do
for hour in 12 1 2 3 4 5 6 7 8 9 10 11; do
halvn=0
if [[ $halve == PM ]] halvn=12

printf "/* %02d:00 %s */\n" $hour $halve
rownum=$(((hour % 12 + halvn)+2))
cat <<CSS
.schedule > .start-${hour}${(L)halve} {
    grid-row-start: ${rownum};
}
.schedule > .end-${hour}${(L)halve} {
    grid-row-end: ${rownum};
}
CSS
done
done
print "/* Auto-generated by timegen.sh end */"
