#!/usr/bin/env zsh

print "<!-- Auto-generated by timegenh.sh begin -->"
halves=(AM PM)
for halve in $halves; do
for hour in 12 1 2 3 4 5 6 7 8 9 10 11; do
nexthour=$(( (hour == 12) ? 1 : hour+1 ))
nexthalve=$(( nexthour == 12 ))
if [[ $nexthalve -eq 1 && $halve == AM ]]; then { nexthalve=PM }
elif [[ $nexthalve -eq 1 && $halve == PM ]]; then { nexthalve=AM }
else { nexthalve=${halve} }
fi

print "<div class=\"hour start-${hour}${(L)halve} end-${nexthour}${(L)nexthalve}\">${hour}:00 ${halve}</div>"

done
done
print "<!-- Auto-generated by timegenh.sh end -->"
